services:
  - type: web
    name: calcom-api
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build --workspace=@calcom/api-proxy
    startCommand: npm run start --workspace=@calcom/api-proxy
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production

