services:
  - type: web
    name: calcom-api
    env: node
    plan: free
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production

  - type: postgres
    name: calcom-db
    plan: free 