services:
  - type: web
    name: calcom-api
    env: node
    plan: free
    buildCommand: cd apps/api && npm install
    startCommand: cd apps/api && npm run dev
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production

