services:
  - type: web
    name: calcom-api
    env: node
    plan: free
    buildCommand: yarn install --immutable
    startCommand: yarn workspace @calcom/api-proxy dev
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production

